source "https://rubygems.org"

# GitHub Pages bundle includes Jekyll, theme, and common plugins
gem "github-pages", group: :jekyll_plugins
gem "just-the-docs"

# Required for running Jekyll with Ruby 3 locally
gem "webrick", "~> 1.8"
